name = "Colony Craft"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "227c1ac919a1ebbc160962e424fc9fa9138a6c7db9813f00e9f515a0404330f4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
