name = "Colony Craft"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "557a6e1418c9a757e6a03460a284bf17722608954a4725b7144cd8f53aba5c46"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
