name = "Colony Craft"
author = "kilaXphantom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b79995b237a628df589da5fcd36c008b1bdc561bb7127344824892246910ff9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
