#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Apr 30 22:50:34 AEST 2026
allowUnknownShaders=false
colorSpace=REC2020
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=8
shaderPack=photon_v1.3b.zip
