#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Apr 25 20:03:12 AEST 2026
allowUnknownShaders=false
colorSpace=REC2020
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=8
shaderPack=ComplementaryReimagined_r5.7.1.zip
