version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = ["immersive_furniture:furniture", "minopp:mino_table", "copycats:copycat_slab", "create:train", "pantographsandwires:pantograph"]
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
farmersdelight = true
create_new_age = true
create_easy_structures = true
gnkinetics = true
wither_spawn_animation = true
extra_gauges = true
easyanvils = true
copycats = true
comforts = true
domum_ornamentum = true
immersive_furniture = true
railways = true
bits_n_bobs = true
phantasm = true
handcrafted = true
rechiseledcreate = true
create_radar = true
creategoggles = true
dndesires = true
offroad = true
apotheosis = true
dynamictreesplus = true
supplementaries = true
createbigcannons = true
create_vibrant_vaults = true
magnumtorch = true
adorablehamsterpets = true
createthrusters = true
endrem = true
create = true
creategbd = true
minecolonies = true
visualworkbench = true
createenchantablemachinery = true
createadditionallogistics = true
multipiston = true
minecraft = true
create_connected = true
powergrid = true
createaddition = true
createframed = true
sliceanddice = true
dragonlib = true
apothic_enchanting = true
create_bb = true
tracks = true
delightfulcreators = true
createhorsepower = true
create_power_loader = true
createendertransmission = true
createfood = true
create_factory_logistics = true
numismatics = true
easymagic = true
oceansdelight = true
brewinandchewin = true
quark = true
another_furniture = true
dndecor = true
minopp = true
createdieselgenerators = true
ends_delight = true
aeronautics_utility_objects = true
create_enchantment_industry = true
custom_nether_portals = true
escalated = true
fastpaintings = true
bellsandwhistles = true
amendments = true
cbc_at = true
tacz = true
minecolonies_compatibility = true
moonlight = true
sophisticatedbackpacks = true
create_tweaked_controllers = true
create_mechanical_spawner = true
create_hypertube = true
corn_delight = true
chipped = true
tfmg = true
pantographsandwires = true
dynamictrees = true
aeronautics = true
createcasing = true
simulated = true
interiors = true
structurize = true
gravestone = true
create_dragons_plus = true
displaydelight = true
lootr = true
createdeco = true
create_mobile_packages = true
dtterralith = true
rechiseled = true
pipeorgans = true
create_integrated_farming = true
