version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = ["immersive_furniture:furniture", "minopp:mino_table"]
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
createfood = true
createendertransmission = true
farmersdelight = true
create_new_age = true
create_easy_structures = true
create_factory_logistics = true
gnkinetics = true
wither_spawn_animation = true
extra_gauges = true
oceansdelight = true
brewinandchewin = true
easymagic = true
numismatics = true
quark = true
another_furniture = true
easyanvils = true
copycats = true
dndecor = true
minopp = true
domum_ornamentum = true
comforts = true
ends_delight = true
createdieselgenerators = true
create_enchantment_industry = true
aeronautics_utility_objects = true
immersive_furniture = true
custom_nether_portals = true
fastpaintings = true
escalated = true
phantasm = true
bellsandwhistles = true
bits_n_bobs = true
cbc_at = true
amendments = true
handcrafted = true
tacz = true
minecolonies_compatibility = true
moonlight = true
rechiseledcreate = true
create_radar = true
sophisticatedbackpacks = true
createthrusters = true
create_tweaked_controllers = true
corn_delight = true
dndesires = true
creategoggles = true
offroad = true
create_mechanical_spawner = true
create_hypertube = true
create_vibrant_vaults = true
createbigcannons = true
dynamictreesplus = true
supplementaries = true
apotheosis = true
magnumtorch = true
dynamictrees = true
minecolonies = true
adorablehamsterpets = true
chipped = true
tfmg = true
endrem = true
create = true
creategbd = true
aeronautics = true
createcasing = true
simulated = true
interiors = true
structurize = true
gravestone = true
visualworkbench = true
multipiston = true
minecraft = true
displaydelight = true
create_dragons_plus = true
lootr = true
create_connected = true
createdeco = true
createaddition = true
powergrid = true
sliceanddice = true
apothic_enchanting = true
dragonlib = true
create_mobile_packages = true
createframed = true
dtterralith = true
create_bb = true
tracks = true
delightfulcreators = true
pipeorgans = true
create_integrated_farming = true
rechiseled = true
createhorsepower = true
